[tool.robotpy]

robotpy_version = "2025.3.2.0"

robotpy_extras = [
    "apriltag",
    "commands2"
]

# Other pip packages to install
requires = [
    "robotpy-pathplannerlib==2025.2.6",
    "phoenix6==25.3.1"
]
